// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using serverWebAPI.Data;

#nullable disable

namespace serverWebAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230922182948_initial2")]
    partial class initial2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("serverWebAPI.Model.BankData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BankName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Bik")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CheckingAccount")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CorrespondentAccount")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("InnId")
                        .HasColumnType("int");

                    b.Property<int?>("IpId")
                        .HasColumnType("int");

                    b.Property<int?>("LimitedLiabilityId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IpId");

                    b.HasIndex("LimitedLiabilityId");

                    b.ToTable("BankDatas");
                });

            modelBuilder.Entity("serverWebAPI.Model.Ip", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<byte[]>("EgrnipScan")
                        .HasColumnType("VARBINARY(MAX)");

                    b.Property<string>("Inn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("InnScan")
                        .HasColumnType("VARBINARY(MAX)");

                    b.Property<bool>("NoAgreement")
                        .HasColumnType("bit");

                    b.Property<string>("Ogrnip")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("OgrnipScan")
                        .HasColumnType("VARBINARY(MAX)");

                    b.Property<byte[]>("PremisesAgreementScan")
                        .HasColumnType("VARBINARY(MAX)");

                    b.Property<string>("RegistrationDate")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Ips");
                });

            modelBuilder.Entity("serverWebAPI.Model.LimitedLiability", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<byte[]>("EgripScan")
                        .HasColumnType("VARBINARY(MAX)");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Inn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("InnScan")
                        .HasColumnType("VARBINARY(MAX)");

                    b.Property<bool>("NoAgreement")
                        .HasColumnType("bit");

                    b.Property<string>("Ogrn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("OgrnScan")
                        .HasColumnType("VARBINARY(MAX)");

                    b.Property<byte[]>("PremisesAgreementScan")
                        .HasColumnType("VARBINARY(MAX)");

                    b.Property<string>("RegistrationDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShortName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("LimitedLiabilities");
                });

            modelBuilder.Entity("serverWebAPI.Model.BankData", b =>
                {
                    b.HasOne("serverWebAPI.Model.Ip", null)
                        .WithMany("BankData")
                        .HasForeignKey("IpId");

                    b.HasOne("serverWebAPI.Model.LimitedLiability", null)
                        .WithMany("BankData")
                        .HasForeignKey("LimitedLiabilityId");
                });

            modelBuilder.Entity("serverWebAPI.Model.Ip", b =>
                {
                    b.Navigation("BankData");
                });

            modelBuilder.Entity("serverWebAPI.Model.LimitedLiability", b =>
                {
                    b.Navigation("BankData");
                });
#pragma warning restore 612, 618
        }
    }
}
